"""session check-ins and daily goal

Revision ID: 91e89799909a
Revises: e9787a0fdcdf
Create Date: 2026-07-29 14:14:22.384071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e89799909a'
down_revision: Union[str, Sequence[str], None] = 'e9787a0fdcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('energy', sa.String(), nullable=True),
    sa.Column('focus_quality', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_checkins_created_at'), 'session_checkins', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_checkins_energy'), 'session_checkins', ['energy'], unique=False)
    op.create_index(op.f('ix_session_checkins_focus_quality'), 'session_checkins', ['focus_quality'], unique=False)
    op.create_index(op.f('ix_session_checkins_id'), 'session_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_session_checkins_session_id'), 'session_checkins', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_checkins_user_id'), 'session_checkins', ['user_id'], unique=False)
    op.add_column('users', sa.Column('daily_goal', sa.Integer(), server_default='6', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_goal')
    op.drop_index(op.f('ix_session_checkins_user_id'), table_name='session_checkins')
    op.drop_index(op.f('ix_session_checkins_session_id'), table_name='session_checkins')
    op.drop_index(op.f('ix_session_checkins_id'), table_name='session_checkins')
    op.drop_index(op.f('ix_session_checkins_focus_quality'), table_name='session_checkins')
    op.drop_index(op.f('ix_session_checkins_energy'), table_name='session_checkins')
    op.drop_index(op.f('ix_session_checkins_created_at'), table_name='session_checkins')
    op.drop_table('session_checkins')
    # ### end Alembic commands ###
