"""presence events

Revision ID: e9787a0fdcdf
Revises: f2dd01052891
Create Date: 2026-07-29 13:07:56.574770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9787a0fdcdf'
down_revision: Union[str, Sequence[str], None] = 'f2dd01052891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('intervention_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presence_events_event_type'), 'presence_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_presence_events_id'), 'presence_events', ['id'], unique=False)
    op.create_index(op.f('ix_presence_events_occurred_at'), 'presence_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_presence_events_user_id'), 'presence_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presence_events_user_id'), table_name='presence_events')
    op.drop_index(op.f('ix_presence_events_occurred_at'), table_name='presence_events')
    op.drop_index(op.f('ix_presence_events_id'), table_name='presence_events')
    op.drop_index(op.f('ix_presence_events_event_type'), table_name='presence_events')
    op.drop_table('presence_events')
    # ### end Alembic commands ###
